# Used to be recursive but Github doesn't cache action downloads so recursion 
# actually is not possible.
# Instead, let's handle up to 3 input paths.
name: 'Save Data'
description: 'Save a list of files with a list of keys'
inputs:
  path_list:  # id of input
    description: 'List of file paths separated by spaces'
    required: true
    default: ''
  name_list:  # id of input
    description: 'List of names for each file separated by spaces'
    required: true
    default: ''
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Get first part of artifact and rest of artifact
      shell: bash
      run: |
          FIRST_PATH=$(echo "${{ inputs.path_list }}" | cut -d " " -f 1)
          SECOND_PATH=$(echo "${{ inputs.path_list }}" | cut -d " " -f 2)
          THIRD_PATH=$(echo "${{ inputs.path_list }}" | cut -d " " -f 3)
          REST_OF_PATHS=$(echo "${{ inputs.path_list }}" | cut -d " " -f2-)
          echo "FIRST_PATH=$FIRST_PATH" >> $GITHUB_ENV
          echo "SECOND_PATH=$SECOND_PATH" >> $GITHUB_ENV
          echo "THIRD_PATH=$THIRD_PATH" >> $GITHUB_ENV
          echo "REST_OF_PATHS=$REST_OF_PATHS" >> $GITHUB_ENV

          FIRST_NAME=$(echo "${{ inputs.name_list }}" | cut -d " " -f 1)
          SECOND_NAME=$(echo "${{ inputs.name_list }}" | cut -d " " -f 2)
          THIRD_NAME=$(echo "${{ inputs.name_list }}" | cut -d " " -f 3)
          REST_OF_NAMES=$(echo "${{ inputs.name_list }}" | cut -d " " -f2-)
          echo "FIRST_NAME=$FIRST_NAME" >> $GITHUB_ENV
          echo "SECOND_NAME=$SECOND_NAME" >> $GITHUB_ENV
          echo "THIRD_NAME=$THIRD_NAME" >> $GITHUB_ENV
          echo "REST_OF_NAMES=$REST_OF_NAMES" >> $GITHUB_ENV
  
    - name: Cache  ${{ env.FIRST_PATH }}
      uses: actions/cache@v3
      if: "${{ env.FIRST_NAME != '' }}"
      env:
        cache-name: cache-${{ env.FIRST_NAME }}-${{ github.run_id }}
      with:
        path: ${{ env.FIRST_PATH }}
        key: cache-${{ env.FIRST_NAME }}-${{ github.run_id }}
  
    - name: Cache  ${{ env.SECOND_PATH }}
      uses: actions/cache@v3
      if: "${{ env.SECOND_PATH != '' }}"
      env:
        cache-name: cache-${{ env.SECOND_NAME }}-${{ github.run_id }}
      with:
        path: ${{ env.SECOND_PATH }}
        key: cache-${{ env.SECOND_NAME }}-${{ github.run_id }}
  
    - name: Cache  ${{ env.THIRD_PATH }}
      uses: actions/cache@v3
      if: "${{ env.THIRD_PATH != '' }}"
      env:
        cache-name: cache-${{ env.THIRD_NAME }}-${{ github.run_id }}
      with:
        path: ${{ env.THIRD_PATH }}
        key: cache-${{ env.THIRD_NAME }}-${{ github.run_id }}
        
    - shell: bash
      run: echo Cached ${{ env.FIRST_NAME }},  ${{ env.SECOND_NAME }},  ${{ env.THIRD_NAME }},.

    # - name: test my example action 
    #   if: "${{ env.REST_OF_PATHS != '' }}"
    #   uses: amhelderman/ci-github-action-save-data@v7
    #   with:
    #     path_list: ${{ env.REST_OF_PATH_LIST }}
    #     name_list: ${{ env.REST_OF_NAME_LIST }}
        

      
