# Used to be recursive but Github doesn't cache action downloads so recursion
# actually is not possible.
# Instead, let's handle up to 3 input paths.
name: 'Share Data Between Jobs'
description: 'Use this action as a step to save up to 3 files, or load up to three files given their keys/names'
inputs:

  path_list:
    description: 'List of file paths separated by spaces'
    required: true
    default: ''

  name_list:
    description: 'List of names for each file separated by spaces'
    required: true
    default: ''

  load:
    description: "string true if loading and not saving"
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Parse the inputs
      shell: bash
      run: |
          FIRST_PATH=$(echo "${{ inputs.path_list }}"  | awk '{print $1}')
          SECOND_PATH=$(echo "${{ inputs.path_list }}" | awk '{print $2}')
          THIRD_PATH=$(echo "${{ inputs.path_list }}"  | awk '{print $3}')
          FIRST_NAME=$(echo "${{ inputs.name_list }}"  | awk '{print $1}')
          SECOND_NAME=$(echo "${{ inputs.name_list }}" | awk '{print $2}')
          THIRD_NAME=$(echo "${{ inputs.name_list }}"  | awk '{print $3}')

          echo "FIRST_PATH=$FIRST_PATH"   >> $GITHUB_ENV
          echo "SECOND_PATH=$SECOND_PATH" >> $GITHUB_ENV
          echo "THIRD_PATH=$THIRD_PATH"   >> $GITHUB_ENV
          echo "FIRST_NAME=$FIRST_NAME"   >> $GITHUB_ENV
          echo "SECOND_NAME=$SECOND_NAME" >> $GITHUB_ENV
          echo "THIRD_NAME=$THIRD_NAME"   >> $GITHUB_ENV

          echo "ENV IS:"
          cat $GITHUB_ENV

    - name: Confirm paths to save contain files.
      if: ${{ inputs.load  == 'false' }}
      shell: bash
      run: |

          if [[ $(echo ${{ env.FIRST_PATH }} | wc -w ) -gt 0 ]]
          then
            if [[ $(find ${{ env.FIRST_PATH }} | wc -l ) -eq 0 ]]
            then
              echo "::warning ::Nothing was found at ${{ env.FIRST_PATH }} to load."
              #echo "Nothing was found at ${{ env.FIRST_PATH }} to save."
              #exit 101
            fi
          fi

          if [[ $(echo ${{ env.SECOND_PATH }} | wc -w ) -gt 0 ]]
          then
            if [[ $(find ${{ env.SECOND_PATH }}  | wc -l) -eq 0 ]]
            then
              echo "::warning ::Nothing was found at ${{ env.SECOND_PATH }} to load."
              # echo "Nothing was found at ${{ env.SECOND_PATH }} to save."
              # exit 102
            fi
          fi

          if [[ $(echo ${{ env.THIRD_PATH }} | wc -w ) -gt 0 ]]
          then
            if [[ $(find ${{ env.THIRD_PATH }} | wc -l) -eq 0 ]]
            then
              echo "::warning ::Nothing was found at ${{ env.THIRD_PATH }} to load."
              # echo "Nothing was found at ${{ env.THIRD_PATH }} to save."
              # exit 103
            fi
          fi


    - name: Cache 1 ${{ env.FIRST_PATH }}
      uses: actions/cache@v3
      if: "${{ env.FIRST_NAME != '' }}"
      with:
        path: ${{ env.FIRST_PATH }}
        key: cache-${{ env.FIRST_NAME }}-${{ github.run_id }}


    - name: Cache 2 ${{ env.SECOND_PATH }}
      uses: actions/cache@v3
      if: "${{ env.SECOND_PATH != '' }}"
      with:
        path: ${{ env.SECOND_PATH }}
        key: cache-${{ env.SECOND_NAME }}-${{ github.run_id }}

    - name: Cache 3 ${{ env.THIRD_PATH }}
      uses: actions/cache@v3
      if: "${{ env.THIRD_PATH != '' }}"
      with:
        path: ${{ env.THIRD_PATH }}
        key: cache-${{ env.THIRD_NAME }}-${{ github.run_id }}


    - name: Confirm loaded path contains files
      if: ${{ inputs.load  == 'true' }}
      shell: bash
      run: |

          if [[ $(echo ${{ env.FIRST_PATH }} | wc -w ) -gt 0 ]]
          then
            if [[ $(find ${{ env.FIRST_PATH }} -maxdepth 1 -type d -printf '%f\n' | wc -w ) -eq 0 ]]
            then
              # ::warning file={name},line={line},endLine={endLine},title={title}::{message}
              echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
              echo "::warning ::Nothing was found at ${{ env.FIRST_PATH }} to load."
              #exit 104
            fi
          fi

          if [[ $(echo ${{ env.SECOND_PATH }} | wc -w ) -gt 0 ]]
          then
            if [[ $(find ${{ env.SECOND_PATH }} -maxdepth 1 -type d -printf '%f\n' | wc -w ) -eq 0 ]]
            then
              echo "::warning ::Nothing was found at ${{ env.SECOND_PATH }} to load."
              #exit 105
            fi
          fi

          if [[ $(echo ${{ env.THIRD_PATH }} | wc -w ) -gt 0 ]]
          then
            if [[ $(find ${{ env.THIRD_PATH }} -maxdepth 1 -type d -printf '%f\n' | wc -w ) -eq 0 ]]
            then
              echo "::warning ::Nothing was found at ${{ env.THIRD_PATH }} to load."
              #echo "Nothing was found at ${{ env.THIRD_PATH }} to load."
              #exit 106
            fi
          fi

